'use client'

import { useEffect, useState, type ReactNode } from 'react'
import { useRouter } from 'next/navigation'

type Product={model_code:string;serial_number:string;warranty_months:number;capacity_kw?:number;product_name?:string}
type RegistrationForm={full_name:string;mobile:string;email:string;address:string;city:string;state:string;pin_code:string;purchase_date:string;invoice_number:string;dealer_name:string;purchase_type:string;installation_date:string;installation_type:string;installer_name:string;installer_mobile:string;installation_address:string;installation_city:string;installation_state:string;installation_pin:string}
const emptyForm:RegistrationForm={full_name:'',mobile:'',email:'',address:'',city:'',state:'',pin_code:'',purchase_date:'',invoice_number:'',dealer_name:'',purchase_type:'Dealer',installation_date:'',installation_type:'Professional',installer_name:'',installer_mobile:'',installation_address:'',installation_city:'',installation_state:'',installation_pin:''}
const displayDate=(v:string)=>v?new Date(v+'T00:00:00').toLocaleDateString('en-IN',{day:'2-digit',month:'short',year:'numeric'}):'—'
async function rpc(url:string,key:string,body:Record<string,unknown>){const fn=String(body.__fn||'');const payload=Object.fromEntries(Object.entries(body).filter(([k])=>k!=='__fn'));const r=await fetch(`${url}/rest/v1/rpc/${fn}`,{method:'POST',headers:{apikey:key,Authorization:`Bearer ${key}`,'Content-Type':'application/json'},body:JSON.stringify(payload),cache:'no-store'});const t=await r.text();let d:any=null;try{d=t?JSON.parse(t):null}catch{}if(!r.ok)throw new Error(typeof d?.message==='string'?d.message:`Request failed (${r.status})`);return d}
function SectionTitle({children}:{children:ReactNode}){return <h2 className="regSectionTitle">{children}</h2>}
function ReviewGrid({items}:{items:[string,string][]}){return <div className="regReviewGrid">{items.map(([label,value])=><div className="regReviewItem" key={label}><span>{label}</span><strong>{value||'—'}</strong></div>)}</div>}

export default function ReviewPage(){
 const router=useRouter();const [serial,setSerial]=useState('');const [product,setProduct]=useState<Product|null>(null);const [form,setForm]=useState<RegistrationForm>(emptyForm);const [loading,setLoading]=useState(true);const [submitting,setSubmitting]=useState(false);const [error,setError]=useState('')
 useEffect(()=>{let cancelled=false;const identifier=new URLSearchParams(window.location.search).get('identifier')?.trim()||'';setSerial(identifier);if(!identifier){setError('No product identifier was received.');setLoading(false);return};const saved=localStorage.getItem(`olitec-registration-${identifier}`);if(saved){try{setForm({...emptyForm,...JSON.parse(saved)})}catch{localStorage.removeItem(`olitec-registration-${identifier}`)}}const url=process.env.NEXT_PUBLIC_SUPABASE_URL;const key=process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY;if(!url||!key){setError('Registration service is not configured.');setLoading(false);return}rpc(url,key,{__fn:'get_product_for_registration',identifier}).then(d=>{if(!cancelled)setProduct(d?.[0]||null)}).catch(e=>{if(!cancelled)setError(e instanceof Error?e.message:'Unable to verify product.')}).finally(()=>{if(!cancelled)setLoading(false)});return()=>{cancelled=true}},[])
 async function confirmRegistration(){if(!product||!serial)return;setSubmitting(true);setError('');const url=process.env.NEXT_PUBLIC_SUPABASE_URL;const key=process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY;if(!url||!key){setError('Registration service is not configured.');setSubmitting(false);return}try{const data=await rpc(url,key,{__fn:'register_product_purchase',identifier:serial,registration:form});const result=data?.[0];if(!result?.registration_number)throw new Error('Registration was not completed. Please try again.');localStorage.removeItem(`olitec-registration-${serial}`);router.push(`/register/success?registration=${encodeURIComponent(result.registration_number)}&start=${encodeURIComponent(result.warranty_start_date)}&end=${encodeURIComponent(result.warranty_end_date)}&serial=${encodeURIComponent(serial)}`)}catch(e){const m=e instanceof Error?e.message:'';if(m.includes('PRODUCT_ALREADY_REGISTERED:'))setError(`This product is already registered. Registration number: ${m.split('PRODUCT_ALREADY_REGISTERED:')[1]}`);else if(m.includes('PRODUCT_NOT_FOUND'))setError('The product could not be verified. Please scan the product QR code again.');else if(m.includes('REQUIRED_CUSTOMER_FIELDS_MISSING'))setError('Please return to the form and complete all required customer and dealer details.');else setError(m||'Registration could not be completed. Please try again.')}finally{setSubmitting(false)}}
 if(loading)return <div className="registrationPage"><main className="regMain"><div className="regLoading">Preparing your review…</div></main></div>
 if(!product)return <div className="registrationPage"><main className="regMain"><div className="regCard regError"><h2>Unable to continue</h2><p>{error||'Product could not be verified.'}</p><button className="regButton primary" onClick={()=>router.push(`/register?identifier=${encodeURIComponent(serial)}`)}>Back to Product</button></div></main></div>
 return <div className="registrationPage"><header className="regHeader"><a className="regLogo" href="/"><img src="/olitec-logo.svg" alt="OLITEC"/></a><button className="regHome" type="button" onClick={()=>router.push('/')}>⌂&nbsp; Home</button></header><main className="regMain"><div className="regTop"><button className="regBack" type="button" onClick={()=>router.push(`/register/purchase?identifier=${encodeURIComponent(serial)}`)}>← Edit details</button></div><section className="regIntro"><span className="regEyebrow">FINAL REVIEW</span><h1>Almost complete.</h1><p>Review the information below before activating your OLITEC warranty.</p></section><section className="regProduct"><div className="regProductImage"><img src="/olitec-generated-hero.jpg" alt="OLITEC solar inverter"/></div><div className="regProductInfo"><span className="regBadge">✓ Product verified</span><h2>{product.model_code}</h2><p>{product.capacity_kw?`${product.capacity_kw} kW `:''}{product.product_name||'OLITEC Solar Inverter'}</p><div className="regProductMeta"><div className="regMetaItem"><small>Serial number</small><strong>{product.serial_number||serial}</strong></div><div className="regMetaItem"><small>Warranty</small><strong>{product.warranty_months/12} Years</strong></div></div></div></section><section className="regCard"><SectionTitle>Customer details</SectionTitle><ReviewGrid items={[["Full name",form.full_name],["Mobile",form.mobile],["Email",form.email],["Address",form.address],["City",form.city],["State",form.state],["PIN code",form.pin_code]]}/></section><section className="regCard"><SectionTitle>Purchase details</SectionTitle><ReviewGrid items={[["Purchase date",displayDate(form.purchase_date)],["Dealer / seller",form.dealer_name],["Invoice number",form.invoice_number],["Purchase type",form.purchase_type],["Invoice","Will be uploaded with registration"]]}/></section><section className="regCard"><SectionTitle>Installation details</SectionTitle><ReviewGrid items={[["Installation date",displayDate(form.installation_date)],["Installation type",form.installation_type],["Installer",form.installer_name],["Installer mobile",form.installer_mobile],["Installation address",form.installation_address],["City",form.installation_city],["State",form.installation_state],["PIN code",form.installation_pin]]}/></section>{error&&<div className="regNote">{error}</div>}<div className="regActions"><button className="regButton primary" disabled={submitting} onClick={confirmRegistration}>{submitting?'Registering…':'Confirm Registration →'}</button></div><div className="regFooter">OLITEC · Clean Energy · Reliable Performance · Smarter Tomorrow</div></main></div>
}
