'use client'

import { useEffect, useState } from 'react'
import { useRouter } from 'next/navigation'

type Product = { model_code: string; serial_number: string; warranty_months: number }
type RegistrationForm = { full_name:string; mobile:string; email:string; address:string; city:string; state:string; pin_code:string; purchase_date:string; invoice_number:string; dealer_name:string; purchase_type:string; installation_date:string; installation_type:string; installer_name:string; installer_mobile:string; installation_address:string; installation_city:string; installation_state:string; installation_pin:string }
const emptyForm: RegistrationForm = {full_name:'',mobile:'',email:'',address:'',city:'',state:'',pin_code:'',purchase_date:'',invoice_number:'',dealer_name:'',purchase_type:'Dealer',installation_date:'',installation_type:'Professional',installer_name:'',installer_mobile:'',installation_address:'',installation_city:'',installation_state:'',installation_pin:''}
const displayDate=(v:string)=>v?new Date(v+'T00:00:00').toLocaleDateString('en-IN',{day:'2-digit',month:'short',year:'numeric'}):'—'
function Row({label,value}:{label:string;value:string}){return <div className="reviewRow"><span>{label}</span><b>{value||'—'}</b></div>}
async function rpc(url:string,key:string,body:unknown){const r=await fetch(`${url}/rest/v1/rpc/${body&&typeof body==='object'&&'__fn' in body?(body as {__fn:string}).__fn:''}`,{method:'POST',headers:{apikey:key,Authorization:`Bearer ${key}`,'Content-Type':'application/json'},body:JSON.stringify(body&&typeof body==='object'?Object.fromEntries(Object.entries(body).filter(([k])=>k!=='__fn')):body),cache:'no-store'});const t=await r.text();let d:any=null;try{d=t?JSON.parse(t):null}catch{};if(!r.ok)throw new Error(typeof d?.message==='string'?d.message:`Request failed (${r.status})`);return d}
export default function StableReviewPage(){
 const router=useRouter(); const [serial,setSerial]=useState(''); const [product,setProduct]=useState<Product|null>(null); const [form,setForm]=useState<RegistrationForm>(emptyForm); const [loading,setLoading]=useState(true); const [submitting,setSubmitting]=useState(false); const [error,setError]=useState('')
 useEffect(()=>{let cancelled=false;const identifier=new URLSearchParams(window.location.search).get('identifier')?.trim()||'';setSerial(identifier);if(!identifier){setError('No product identifier was received.');setLoading(false);return};const key=`olitec-registration-${identifier}`;const saved=localStorage.getItem(key);if(saved){try{setForm({...emptyForm,...JSON.parse(saved)})}catch{localStorage.removeItem(key)}};const url=process.env.NEXT_PUBLIC_SUPABASE_URL;const pub=process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY;if(!url||!pub){setError('Registration service is not configured.');setLoading(false);return};rpc(url,pub,{__fn:'get_product_for_registration',identifier}).then(d=>{if(!cancelled)setProduct(d?.[0]||null)}).catch(e=>{if(!cancelled)setError(e instanceof Error?e.message:'Unable to verify product.')}).finally(()=>{if(!cancelled)setLoading(false)});return()=>{cancelled=true}},[])
 async function confirmRegistration(){if(!product||!serial)return;setSubmitting(true);setError('');const url=process.env.NEXT_PUBLIC_SUPABASE_URL;const pub=process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY;if(!url||!pub){setError('Registration service is not configured.');setSubmitting(false);return}try{const data=await rpc(url,pub,{__fn:'register_product_purchase',identifier:serial,registration:form});const result=data?.[0];if(!result?.registration_number)throw new Error('Registration was not completed. Please try again.');localStorage.removeItem(`olitec-registration-${serial}`);router.push(`/register/success?registration=${encodeURIComponent(result.registration_number)}&start=${encodeURIComponent(result.warranty_start_date)}&end=${encodeURIComponent(result.warranty_end_date)}&serial=${encodeURIComponent(serial)}`)}catch(e){const m=e instanceof Error?e.message:'';if(m.includes('PRODUCT_ALREADY_REGISTERED:'))setError(`This product is already registered. Registration number: ${m.split('PRODUCT_ALREADY_REGISTERED:')[1]}`);else if(m.includes('PRODUCT_NOT_FOUND'))setError('The product could not be verified. Please scan the product QR code again.');else if(m.includes('REQUIRED_CUSTOMER_FIELDS_MISSING'))setError('Please return to the form and complete all required customer and dealer details.');else setError(m||'Registration could not be completed. Please try again.')}finally{setSubmitting(false)}}
 if(loading)return <div className="app"><main><section className="card"><p>Loading review…</p></section></main></div>
 if(!product)return <div className="app"><main><section className="card"><h2>Unable to continue</h2><p>{error||'Product could not be verified.'}</p><button className="btn secondary" onClick={()=>router.push(`/register?identifier=${encodeURIComponent(serial)}`)}>Back to Product</button></section></main></div>
 return <div className="app"><header><div style={{fontWeight:800,fontSize:28,letterSpacing:1}}>OLITEC</div><div className="lang">English⌄</div></header><main>
  <button className="back" onClick={()=>router.push(`/register/purchase?identifier=${encodeURIComponent(serial)}`)}>← Edit details</button>
  <div className="steps"><div className="step active"><div className="dot">✓</div>Product</div><div className="step active"><div className="dot">✓</div>Details</div><div className="step active"><div className="dot">3</div>Review</div><div className="step"><div className="dot">4</div>Complete</div></div>
  <section className="card"><span className="badge">Review before submission</span><h2 style={{marginTop:12}}>Check your details</h2><p>Please confirm that the information below is correct before completing your OLITEC registration.</p></section>
  <section className="card"><h2>Product</h2><Row label="Model" value={product.model_code}/><Row label="Serial number" value={product.serial_number||serial}/><Row label="Warranty" value={product.warranty_months?`${product.warranty_months/12} years`:''}/></section>
  <section className="card"><h2>Customer details</h2><Row label="Full name" value={form.full_name}/><Row label="Mobile" value={form.mobile}/><Row label="Email" value={form.email}/><Row label="Address" value={form.address}/><Row label="City" value={form.city}/><Row label="State" value={form.state}/><Row label="PIN code" value={form.pin_code}/></section>
  <section className="card"><h2>Purchase details</h2><Row label="Purchase date" value={displayDate(form.purchase_date)}/><Row label="Dealer / seller" value={form.dealer_name}/><Row label="Invoice number" value={form.invoice_number}/><Row label="Purchase type" value={form.purchase_type}/><Row label="Invoice" value="Will be uploaded with registration"/></section>
  <section className="card"><h2>Installation details</h2><Row label="Installation date" value={displayDate(form.installation_date)}/><Row label="Installation type" value={form.installation_type}/><Row label="Installer" value={form.installer_name}/><Row label="Installer mobile" value={form.installer_mobile}/><Row label="Installation address" value={form.installation_address}/></section>
  {error&&<div className="note" style={{marginTop:12,color:'#9d2d22'}}>{error}</div>}<button className="btn primary" style={{marginTop:12}} disabled={submitting} onClick={confirmRegistration}>{submitting?'Registering…':'Confirm Registration →'}</button>
 </main><footer>OLITEC · Clean Energy · Reliable Performance · Smarter Tomorrow</footer></div>
}
