'use client'

import { useEffect, useMemo, useState } from 'react'
import { supabase } from '@/lib/supabase'

type RegistrationRow = {
  registration_number:string; registered_at:string; full_name:string; mobile:string; email:string|null; address:string; city:string; state:string; pin_code:string; purchase_date:string|null; invoice_number:string|null; dealer_name:string|null; serial_number:string; model_code:string; product_name:string|null; capacity_kw:number|null; product_image_url:string|null; warranty_start_date:string; warranty_end_date:string; warranty_status:string; complaint_count:number; open_complaint_count:number
}

const s:Record<string,React.CSSProperties>={page:{minHeight:'100vh',background:'#f7f9fb',color:'#172033'},shell:{maxWidth:1500,margin:'0 auto',padding:'28px 34px 60px'},header:{display:'flex',justifyContent:'space-between',alignItems:'center',gap:20,marginBottom:24},actions:{display:'flex',gap:10,flexWrap:'wrap',justifyContent:'flex-end'},button:{border:'1px solid #dfe5ec',borderRadius:11,padding:'10px 15px',fontWeight:800,cursor:'pointer',background:'#fff',color:'#172033'},primary:{border:0,borderRadius:12,padding:'12px 18px',fontWeight:800,cursor:'pointer',background:'#172033',color:'#fff'},card:{background:'#fff',border:'1px solid #e4e9ef',borderRadius:22,padding:22,boxShadow:'0 10px 35px rgba(23,32,51,.05)'},input:{width:'100%',height:48,padding:'12px 14px',border:'1px solid #dfe3ea',borderRadius:12,background:'#fff',color:'#172033'},tab:{border:'1px solid #dfe5ec',borderRadius:12,padding:'11px 18px',fontWeight:800,cursor:'pointer',background:'#fff',color:'#172033'},active:{border:0,borderRadius:12,padding:'11px 18px',fontWeight:800,cursor:'pointer',background:'#172033',color:'#fff'}}

function fmt(v:string|null|undefined){return v?new Date(v+'T00:00:00').toLocaleDateString('en-IN',{day:'2-digit',month:'short',year:'numeric'}):'—'}
function fmtDateTime(v:string){return new Date(v).toLocaleString('en-IN',{day:'2-digit',month:'short',year:'numeric',hour:'2-digit',minute:'2-digit'})}

export default function ProductRegistrationHistory(){
 const [rows,setRows]=useState<RegistrationRow[]>([]);const [search,setSearch]=useState('');const [loading,setLoading]=useState(true);const [error,setError]=useState('');const [selected,setSelected]=useState<string|null>(null)
 async function load(){setLoading(true);setError('');const {data,error}=await supabase.rpc('admin_get_product_registration_history',{p_search:search.trim()||null,p_limit:500,p_offset:0});if(error)setError(error.message.includes('PRODUCT_ADMIN_ACCESS_REQUIRED')?'Your account does not have Product Admin permission.':error.message);else setRows((data||[]) as RegistrationRow[]);setLoading(false)}
 useEffect(()=>{load()},[])
 const groups=useMemo(()=>{const map=new Map<string,RegistrationRow[]>();rows.forEach(r=>{const a=map.get(r.registration_number)||[];a.push(r);map.set(r.registration_number,a)});return Array.from(map.entries()).map(([registration_number,items])=>({registration_number,items,first:items[0]}))},[rows])
 const current=groups.find(g=>g.registration_number===selected)
 return <div style={s.page}><div style={s.shell}>
  <header style={s.header}><div><img src="/olitec-logo.svg" alt="OLITEC" style={{width:170}}/><div style={{color:'#718096',fontSize:14,marginTop:5}}>Product Registration History</div></div><div style={s.actions}><button style={s.button} onClick={()=>window.location.href='/admin/products'}>← Product Admin</button><button style={s.button} onClick={()=>window.location.href='/admin'}>Admin Home</button><button style={s.button} onClick={load}>↻ Refresh</button></div></header>
  <div style={{display:'flex',gap:10,marginBottom:18,flexWrap:'wrap'}}><button style={s.tab} onClick={()=>window.location.href='/admin/products'}>Product Master</button><button style={s.tab} onClick={()=>window.location.href='/admin/products#serials'}>Serial Number Generator</button><button style={s.active}>Product Registration History</button></div>
  <section style={s.card}><div style={{display:'flex',justifyContent:'space-between',alignItems:'end',gap:15,flexWrap:'wrap'}}><div><div style={{fontSize:11,letterSpacing:'.12em',fontWeight:800,color:'#168a45'}}>CUSTOMER REGISTRATIONS</div><h1 style={{margin:'6px 0 4px',fontSize:28}}>Product Registration History</h1><p style={{margin:0,color:'#718096'}}>Search registrations, customers, serial numbers and related product details.</p></div><div style={{minWidth:320,flex:'0 1 520px',display:'flex',gap:8}}><input style={s.input} value={search} onChange={e=>setSearch(e.target.value)} onKeyDown={e=>{if(e.key==='Enter')load()}} placeholder="Search registration, serial, customer, email, mobile or model"/><button style={s.primary} onClick={load} disabled={loading}>Search</button></div></div>
  {error&&<div style={{marginTop:18,padding:13,borderRadius:13,background:'#fff0f0',color:'#b42318'}}>{error}</div>}
  <div style={{marginTop:22,overflowX:'auto'}}>{loading?<div style={{padding:35,textAlign:'center',color:'#718096'}}>Loading registration history…</div>:groups.length===0?<div style={{padding:45,textAlign:'center',color:'#718096'}}>No product registrations found.</div>:<table style={{width:'100%',borderCollapse:'collapse',minWidth:1050}}><thead><tr>{['Registration','Customer','Products','Registered','Warranty','Complaints',''].map(h=><th key={h} style={{textAlign:'left',padding:'13px 12px',borderBottom:'1px solid #e6ebf0',fontSize:12,color:'#64748b'}}>{h}</th>)}</tr></thead><tbody>{groups.map(g=><tr key={g.registration_number}><td style={{padding:'15px 12px',fontWeight:800}}>{g.registration_number}</td><td style={{padding:'15px 12px'}}><div style={{fontWeight:800}}>{g.first.full_name}</div><div style={{fontSize:12,color:'#718096'}}>{g.first.mobile}</div><div style={{fontSize:12,color:'#718096'}}>{g.first.email||'No email'}</div></td><td style={{padding:'15px 12px'}}><strong>{g.items.length}</strong> product{g.items.length===1?'':'s'}<div style={{fontSize:12,color:'#718096',marginTop:4}}>{g.items.slice(0,2).map(x=>x.serial_number).join(', ')}{g.items.length>2?' …':''}</div></td><td style={{padding:'15px 12px',whiteSpace:'nowrap'}}>{fmtDateTime(g.first.registered_at)}</td><td style={{padding:'15px 12px'}}><span style={{fontWeight:800}}>{g.first.warranty_status}</span><div style={{fontSize:12,color:'#718096'}}>{fmt(g.first.warranty_start_date)} – {fmt(g.first.warranty_end_date)}</div></td><td style={{padding:'15px 12px'}}>{g.first.complaint_count}{g.first.open_complaint_count>0?<div style={{fontSize:12,color:'#b54708'}}>{g.first.open_complaint_count} open</div>:null}</td><td style={{padding:'15px 12px'}}><button style={s.button} onClick={()=>setSelected(g.registration_number)}>View Details</button></td></tr>)}</tbody></table>}</div>
  </section>
  {current&&<div onClick={()=>setSelected(null)} style={{position:'fixed',inset:0,background:'rgba(15,23,42,.45)',display:'flex',alignItems:'center',justifyContent:'center',padding:20,zIndex:20}}><section onClick={e=>e.stopPropagation()} style={{...s.card,width:'100%',maxWidth:1050,maxHeight:'90vh',overflowY:'auto'}}><div style={{display:'flex',justifyContent:'space-between',alignItems:'start',gap:15}}><div><div style={{fontSize:11,letterSpacing:'.12em',fontWeight:800,color:'#168a45'}}>REGISTRATION</div><h2 style={{margin:'5px 0'}}>{current.registration_number}</h2><div style={{color:'#718096',fontSize:13}}>Registered {fmtDateTime(current.first.registered_at)}</div></div><button style={s.button} onClick={()=>setSelected(null)}>Close</button></div>
   <div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(220px,1fr))',gap:12,marginTop:20}}>{[['Customer',current.first.full_name],['Mobile',current.first.mobile],['Email',current.first.email||'—'],['Address',[current.first.address,current.first.city,current.first.state,current.first.pin_code].filter(Boolean).join(', ')||'—'],['Purchase Date',fmt(current.first.purchase_date)],['Invoice',current.first.invoice_number||'—'],['Dealer',current.first.dealer_name||'—']].map(([k,v])=><div key={k} style={{padding:14,border:'1px solid #e6ebf0',borderRadius:14}}><div style={{fontSize:11,fontWeight:800,color:'#64748b'}}>{k}</div><div style={{marginTop:5,fontWeight:700,wordBreak:'break-word'}}>{v}</div></div>)}</div>
   <h3 style={{margin:'25px 0 12px'}}>Registered Products</h3><div style={{display:'grid',gap:10}}>{current.items.map(item=><div key={item.serial_number} style={{display:'grid',gridTemplateColumns:'72px 1fr auto',gap:14,alignItems:'center',padding:14,border:'1px solid #e6ebf0',borderRadius:15}}>{item.product_image_url?<img src={item.product_image_url} alt={item.product_name||item.model_code} style={{width:72,height:72,objectFit:'contain',borderRadius:10,background:'#f7f9fb'}}/>:<div style={{width:72,height:72,borderRadius:10,background:'#f1f4f7'}}/>}<div><div style={{fontWeight:800}}>{item.product_name||'OLITEC Product'}</div><div style={{fontSize:13,color:'#475569'}}>Model: {item.model_code} · Serial: {item.serial_number}</div><div style={{fontSize:12,color:'#718096'}}>Capacity: {item.capacity_kw??'—'} kW · Warranty: {fmt(item.warranty_start_date)} – {fmt(item.warranty_end_date)}</div></div><div style={{textAlign:'right',fontWeight:800}}>{item.warranty_status}<div style={{fontSize:12,color:item.open_complaint_count?'#b54708':'#718096'}}>{item.complaint_count} complaint{item.complaint_count===1?'':'s'}</div></div></div>)}</div>
   </section></div>}
 </div></div>
}
