'use client'

import { useEffect, useState } from 'react'
import { useRouter } from 'next/navigation'

type Product={serial_number:string;model_code:string;product_name:string;capacity_kw:number;warranty_months:number;manufacturing_date:string|null}
const fmt=(v:string)=>v?new Date(v+'T00:00:00').toLocaleDateString('en-IN',{day:'2-digit',month:'short',year:'numeric'}):'—'
async function getProduct(serial:string):Promise<Product|null>{const url=process.env.NEXT_PUBLIC_SUPABASE_URL;const key=process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY;if(!url||!key)return null;const r=await fetch(`${url}/rest/v1/rpc/get_product_for_registration`,{method:'POST',headers:{apikey:key,Authorization:`Bearer ${key}`,'Content-Type':'application/json'},body:JSON.stringify({identifier:serial}),cache:'no-store'});if(!r.ok)return null;const data=await r.json();return data?.[0]??null}
export default function RegistrationSuccessPage(){
 const router=useRouter();const [product,setProduct]=useState<Product|null>(null);const [qrDataUrl,setQrDataUrl]=useState('');const [downloading,setDownloading]=useState(false);const [loading,setLoading]=useState(true);const [error,setError]=useState('')
 useEffect(()=>{let active=true;async function load(){try{const q=new URLSearchParams(window.location.search);const registration=q.get('registration')||'';const start=q.get('start')||'';const end=q.get('end')||'';const serial=q.get('serial')||'';if(!registration||!serial){if(active)setError('Registration details are missing. Please complete the registration again.');return}const p=await getProduct(serial);if(active)setProduct(p);const QRCode=(await import('qrcode')).default;const qr=await QRCode.toDataURL(`${window.location.origin}/warranty/${encodeURIComponent(registration)}`,{width:420,margin:3,errorCorrectionLevel:'M'});if(active)setQrDataUrl(qr);sessionStorage.setItem('olitec-success',JSON.stringify({registration,start,end,serial}))}catch(e){console.error(e);if(active)setError('The warranty card could not be prepared. Please refresh the page.')}finally{if(active)setLoading(false)}}load();return()=>{active=false}},[])
 async function downloadWarrantyCard(){const saved=sessionStorage.getItem('olitec-success');if(!saved||!qrDataUrl)return;setDownloading(true);try{const {registration,start,end,serial}=JSON.parse(saved);const {jsPDF}=await import('jspdf');const doc=new jsPDF({orientation:'landscape',unit:'mm',format:'a5'});doc.setFillColor(255,255,255);doc.rect(0,0,210,148,'F');doc.setDrawColor(232,158,20);doc.setLineWidth(1.2);doc.roundedRect(8,8,194,132,6,6,'S');doc.setTextColor(23,32,51);doc.setFont('helvetica','bold');doc.setFontSize(23);doc.text('OLITEC',16,23);doc.setFontSize(10);doc.setTextColor(90,99,115);doc.setFont('helvetica','normal');doc.text('SOLAR INVERTER WARRANTY CARD',16,30);doc.setTextColor(23,32,51);doc.setFont('helvetica','bold');doc.setFontSize(15);doc.text(product?.model_code||'OLITEC Solar Inverter',16,45);doc.setFont('helvetica','normal');doc.setFontSize(10);doc.text(`Product: ${product?.product_name||'OLITEC Solar Inverter'}`,16,53);doc.text(`Capacity: ${product?.capacity_kw??'—'} kW`,16,60);doc.text(`Serial Number: ${product?.serial_number||serial}`,16,67);doc.text(`Registration Number: ${registration}`,16,74);doc.text(`Warranty: ${fmt(start)} to ${fmt(end)}`,16,81);doc.text(`Manufacturing Date: ${product?.manufacturing_date?fmt(product.manufacturing_date):'—'}`,16,88);doc.setDrawColor(225,225,225);doc.line(16,96,128,96);doc.setFontSize(8.5);doc.setTextColor(105,112,125);doc.text('Scan the QR code to verify this registration.',16,105);doc.text('Keep this warranty card and your purchase invoice safely.',16,111);doc.setFont('helvetica','bold');doc.setTextColor(23,32,51);doc.text('OLITEC · Clean Energy · Reliable Performance · Smarter Tomorrow',16,129);doc.addImage(qrDataUrl,'PNG',153,42,38,38);doc.setFontSize(7.5);doc.setFont('helvetica','normal');doc.setTextColor(105,112,125);doc.text('Registration QR',172,85,{align:'center'});doc.save(`${registration}-OLITEC-Warranty-Card.pdf`)}catch(e){console.error(e);alert('Unable to create the warranty card. Please try again.')}finally{setDownloading(false)}}
 if(loading)return <div className="registrationPage"><main className="regMain"><div className="regLoading">Preparing your warranty registration…</div></main></div>
 if(error)return <div className="registrationPage"><main className="regMain"><div className="regCard regError"><div className="regCheck">✓</div><h2>Registration received</h2><p>{error}</p><button className="regButton primary" onClick={()=>router.push('/')}>Back to OLITEC</button></div></main></div>
 const saved=typeof window!=='undefined'?sessionStorage.getItem('olitec-success'):null;const details=saved?JSON.parse(saved):{registration:'',start:'',end:'',serial:''}
 return <div className="registrationPage"><header className="regHeader"><a className="regLogo" href="/"><img src="/olitec-logo.svg" alt="OLITEC"/></a><button className="regHome" type="button" onClick={()=>router.push('/')}>⌂&nbsp; Home</button></header><main className="regMain"><div className="regTop"><button className="regBack" type="button" onClick={()=>router.push('/')}>← Back to Home</button></div><section className="regIntro"><span className="regEyebrow">WARRANTY ACTIVATED</span><h1>You're all set.</h1><p>Your OLITEC product has been registered successfully. Keep your registration number for future service requests.</p></section><section className="regCard regSuccess"><div className="regCheck">✓</div><span className="regBadge">Registration received</span><h1>Thank you!</h1><p>Your warranty registration is now complete.</p><div className="regRegistrationNo"><small>Registration number</small><strong>{details.registration}</strong></div>{product&&<div className="regSuccessProduct"><strong>{product.model_code} · {product.serial_number}</strong><br/>{product.capacity_kw} kW {product.product_name}<br/><span style={{color:'#647991'}}>Warranty: {fmt(details.start)} to {fmt(details.end)}</span></div>}{qrDataUrl&&<><img className="regQr" src={qrDataUrl} alt="Registration QR code"/><small style={{color:'#71849b'}}>Scan to verify your warranty registration</small></>}<div className="regActions" style={{justifyContent:'center',marginTop:22}}><button className="regButton primary" disabled={!qrDataUrl||downloading} onClick={downloadWarrantyCard}>{downloading?'Preparing Warranty Card…':'Download Warranty Card (PDF)'}</button><button className="regButton" onClick={()=>router.push('/')}>Back to OLITEC</button></div></section><div className="regFooter">OLITEC · Clean Energy · Reliable Performance · Smarter Tomorrow</div></main></div>
}
