'use client'

import { FormEvent, useEffect, useMemo, useState, type CSSProperties } from 'react'
import { supabase } from '@/lib/supabase'

const styles: Record<string, CSSProperties> = {
  page:{minHeight:'100vh',background:'#f7f9fb',color:'#172033'}, shell:{maxWidth:1440,margin:'0 auto',padding:'28px 34px 50px'}, header:{display:'flex',justifyContent:'space-between',alignItems:'center',gap:20,marginBottom:24}, logo:{fontSize:30,fontWeight:800,letterSpacing:'.04em'}, sub:{fontSize:14,color:'#718096',marginTop:4}, actions:{display:'flex',gap:10}, button:{border:'1px solid #e2e8f0',borderRadius:11,padding:'10px 15px',fontWeight:700,cursor:'pointer',background:'#fff',color:'#172033'}, primary:{border:0,borderRadius:12,padding:'13px 18px',fontWeight:800,cursor:'pointer',background:'#ff7a00',color:'#fff'}, grid:{display:'grid',gridTemplateColumns:'minmax(360px,480px) 1fr',gap:18,alignItems:'start'}, card:{background:'#fff',border:'1px solid #e6e9ef',borderRadius:22,padding:24,boxShadow:'0 10px 35px rgba(23,32,51,.05)'}, label:{display:'block',fontSize:12,fontWeight:800,color:'#475569',margin:'15px 0 7px'}, input:{width:'100%',height:48,padding:'12px 14px',border:'1px solid #dfe3ea',borderRadius:12,background:'#fff',color:'#172033'}, tableHead:{display:'grid',gridTemplateColumns:'1.1fr 1.6fr .8fr 1fr 1.4fr',gap:12,padding:'11px 14px',background:'#fafbfc',color:'#98a2b3',fontSize:10,textTransform:'uppercase',letterSpacing:'.07em',fontWeight:800}, row:{display:'grid',gridTemplateColumns:'1.1fr 1.6fr .8fr 1fr 1.4fr',gap:12,alignItems:'center',padding:'14px',borderTop:'1px solid #eef1f5',fontSize:12}, alert:{padding:'12px 15px',borderRadius:13,fontSize:13,marginBottom:15}, image:{width:52,height:52,objectFit:'cover',borderRadius:10,border:'1px solid #e6e9ef',background:'#f7f9fb'}
}

type ProductRow={model_id:string;model_code:string;product_name:string;capacity_kw:number|null;warranty_months:number;image_url:string|null;product_id:string|null;serial_number:string|null;qr_code:string|null;manufacturing_date:string|null;batch_number:string|null;product_status:string|null}
type Generated={model_code:string;serial_number:string;qr_code:string;manufacturing_date:string;batch_number:string}

function errorText(value:any){return value?.message||value?.details||value?.hint||'Something went wrong.'}

export default function AdminProductsPage(){
 const [email,setEmail]=useState('');const [password,setPassword]=useState('');const [loggedIn,setLoggedIn]=useState(false);const [loading,setLoading]=useState(false);const [error,setError]=useState('');const [message,setMessage]=useState('');const [rows,setRows]=useState<ProductRow[]>([]);const [generated,setGenerated]=useState<Generated[]>([])
 const [form,setForm]=useState({model_code:'',product_name:'',capacity_kw:'',warranty_months:'60',manufacturing_date:new Date().toISOString().slice(0,10),quantity:'1'})
 const [image,setImage]=useState<File|null>(null);const [preview,setPreview]=useState('')

 useEffect(()=>{supabase.auth.getSession().then(({data})=>{if(data.session){setLoggedIn(true);loadCatalog()}})},[])
 async function loadCatalog(){setLoading(true);setError('');const {data,error}=await supabase.rpc('admin_get_product_catalog');if(error)setError(errorText(error));else setRows((data||[]) as ProductRow[]);setLoading(false)}
 async function login(event:FormEvent){event.preventDefault();setLoading(true);setError('');const {error}=await supabase.auth.signInWithPassword({email,password});if(error){setError(errorText(error));setLoading(false);return}setLoggedIn(true);await loadCatalog()}
 async function logout(){await supabase.auth.signOut();setLoggedIn(false);setRows([]);setGenerated([])}
 function setField(key:string,value:string){setForm(v=>({...v,[key]:value}))}
 function chooseImage(file:File|null){setImage(file);if(preview)URL.revokeObjectURL(preview);setPreview(file?URL.createObjectURL(file):'')}
 async function submit(event:FormEvent){event.preventDefault();setLoading(true);setError('');setMessage('');setGenerated([]);try{
   let imageUrl:string|null=null
   if(image){if(image.size>5*1024*1024)throw new Error('Product image must be 5 MB or smaller.');if(!['image/jpeg','image/png','image/webp'].includes(image.type))throw new Error('Use JPG, PNG or WebP for the product image.');const path=`models/${Date.now()}-${image.name.replace(/[^a-zA-Z0-9._-]/g,'_')}`;const upload=await supabase.storage.from('products').upload(path,image,{upsert:false,contentType:image.type});if(upload.error)throw upload.error;imageUrl=supabase.storage.from('products').getPublicUrl(path).data.publicUrl}
   const {data,error}=await supabase.rpc('admin_create_product_batch',{p_model_code:form.model_code,p_product_name:form.product_name,p_capacity_kw:form.capacity_kw?Number(form.capacity_kw):null,p_warranty_months:Number(form.warranty_months),p_manufacturing_date:form.manufacturing_date,p_quantity:Number(form.quantity),p_image_url:imageUrl});if(error)throw error;setGenerated((data||[]) as Generated[]);setMessage(`${(data||[]).length} serial number${(data||[]).length===1?'':'s'} generated successfully.`);await loadCatalog()
 }catch(err){setError(errorText(err))}finally{setLoading(false)}}
 const uniqueModels=useMemo(()=>Array.from(new Map(rows.map(r=>[r.model_id,r])).values()),[rows])
 function downloadCsv(){if(!generated.length)return;const header='Model,Serial Number,QR Code,Production Date,Batch Number';const lines=generated.map(r=>[r.model_code,r.serial_number,r.qr_code,r.manufacturing_date,r.batch_number].map(v=>`"${String(v).replace(/"/g,'""')}"`).join(','));const blob=new Blob([header+'\n'+lines.join('\n')],{type:'text/csv;charset=utf-8'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`OLITEC-${generated[0].model_code}-serials.csv`;a.click();URL.revokeObjectURL(url)}

 if(!loggedIn)return <div style={{...styles.page,display:'flex',alignItems:'center',justifyContent:'center',padding:20}}><section style={{...styles.card,width:'100%',maxWidth:520}}><div style={{fontSize:30,fontWeight:800}}>OLITEC</div><div style={styles.sub}>Product & Service Administration</div><div style={{marginTop:28,fontSize:11,letterSpacing:'.12em',fontWeight:800,color:'#2d9b4c'}}>PRODUCT MANAGEMENT</div><h1 style={{fontSize:27,margin:'8px 0'}}>Sign in to manage products</h1><p style={{color:'#718096'}}>Use the authorised OLITEC service desk account.</p><form onSubmit={login}><label style={styles.label}>Staff email</label><input style={styles.input} type="email" value={email} onChange={e=>setEmail(e.target.value)} required/><label style={styles.label}>Password</label><input style={styles.input} type="password" value={password} onChange={e=>setPassword(e.target.value)} required/>{error&&<div style={{...styles.alert,background:'#fff0f0',color:'#b42318',border:'1px solid #ffd4d1',marginTop:15}}>{error}</div>}<button style={{...styles.primary,width:'100%',marginTop:18}} disabled={loading}>{loading?'Signing in…':'Sign in →'}</button></form></section></div>

 return <div style={styles.page}><div style={styles.shell}>
  <header style={styles.header}><div><div style={styles.logo}>OLITEC</div><div style={styles.sub}>Product & Service Administration</div></div><div style={styles.actions}><button style={styles.button} onClick={()=>window.location.href='/admin/service'}>Service Complaints</button><button style={styles.button} onClick={loadCatalog}>↻ Refresh</button><button style={{...styles.button,background:'#172033',color:'#fff'}} onClick={logout}>Sign out</button></div></header>
  {error&&<div style={{...styles.alert,background:'#fff0f0',color:'#b42318',border:'1px solid #ffd4d1'}}>{error}</div>}{message&&<div style={{...styles.alert,background:'#edf9f0',color:'#258b42',border:'1px solid #d4efd9'}}>✓ {message}</div>}
  <div style={styles.grid}>
   <section style={styles.card}><div style={{fontSize:11,letterSpacing:'.12em',fontWeight:800,color:'#2d9b4c'}}>PRODUCT ENTRY</div><h2 style={{fontSize:23,margin:'6px 0'}}>Create production batch</h2><p style={{color:'#718096',fontSize:13}}>Enter the model and production details. Serial numbers are generated automatically from model + production month + running sequence.</p><form onSubmit={submit}>
    <label style={styles.label}>Model number *</label><input style={styles.input} value={form.model_code} onChange={e=>setField('model_code',e.target.value)} placeholder="e.g. OL-5KTL" required/>
    <label style={styles.label}>Product name *</label><input style={styles.input} value={form.product_name} onChange={e=>setField('product_name',e.target.value)} placeholder="e.g. OLITEC Solar Inverter" required/>
    <div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:10}}><div><label style={styles.label}>Capacity (kW)</label><input style={styles.input} type="number" min="0" step="0.1" value={form.capacity_kw} onChange={e=>setField('capacity_kw',e.target.value)} placeholder="5"/></div><div><label style={styles.label}>Warranty (months) *</label><input style={styles.input} type="number" min="1" value={form.warranty_months} onChange={e=>setField('warranty_months',e.target.value)} required/></div></div>
    <div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:10}}><div><label style={styles.label}>Production date *</label><input style={styles.input} type="date" value={form.manufacturing_date} onChange={e=>setField('manufacturing_date',e.target.value)} required/></div><div><label style={styles.label}>Quantity *</label><input style={styles.input} type="number" min="1" max="10000" value={form.quantity} onChange={e=>setField('quantity',e.target.value)} required/></div></div>
    <label style={styles.label}>Product image</label><input style={{...styles.input,height:'auto',padding:10}} type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>chooseImage(e.target.files?.[0]||null)}/>{preview&&<div style={{marginTop:10,display:'flex',alignItems:'center',gap:10}}><img src={preview} alt="Preview" style={styles.image}/><span style={{fontSize:12,color:'#64748b'}}>{image?.name}</span></div>}
    <button style={{...styles.primary,width:'100%',marginTop:20}} disabled={loading}>{loading?'Creating batch…':'Generate Product Serial Numbers →'}</button>
   </form>
   <div style={{marginTop:18,padding:13,borderRadius:13,background:'#f8fafc',fontSize:12,color:'#64748b'}}><strong style={{color:'#172033'}}>Serial format:</strong> model code without punctuation + YYMM + six-digit running sequence.<br/>Example: <b style={{color:'#172033'}}>OL5KTL2609000001</b></div>
   </section>

   <section style={styles.card}><div style={{display:'flex',justifyContent:'space-between',gap:10,alignItems:'center'}}><div><div style={{fontSize:11,letterSpacing:'.12em',fontWeight:800,color:'#2d9b4c'}}>PRODUCT MASTER</div><h2 style={{fontSize:23,margin:'6px 0'}}>Registered product inventory</h2></div><span style={{fontSize:12,color:'#64748b'}}>{uniqueModels.length} model{uniqueModels.length===1?'':'s'} · {rows.filter(r=>r.product_id).length} units</span></div>
    <div style={{overflowX:'auto',marginTop:18}}><div style={{minWidth:760}}><div style={styles.tableHead}><span>Model</span><span>Product</span><span>Capacity</span><span>Warranty</span><span>Serial / Production</span></div>{loading&&!rows.length?<div style={{padding:30,textAlign:'center',color:'#64748b'}}>Loading products…</div>:rows.map((r,i)=><div style={styles.row} key={r.product_id||`${r.model_id}-${i}`}><div style={{display:'flex',gap:9,alignItems:'center'}}>{r.image_url?<img src={r.image_url} alt="" style={styles.image}/>:<div style={{...styles.image,display:'grid',placeItems:'center',fontSize:9,color:'#94a3b8'}}>No image</div>}<strong>{r.model_code}</strong></div><div>{r.product_name}</div><div>{r.capacity_kw??'—'} kW</div><div>{r.warranty_months} months</div><div><strong>{r.serial_number||'—'}</strong><small style={{display:'block',color:'#94a3b8',marginTop:3}}>{r.manufacturing_date||'—'} · {r.product_status||'—'}</small></div></div>)}</div></div>
   </section>
  </div>
  {generated.length>0&&<section style={{...styles.card,marginTop:18}}><div style={{display:'flex',justifyContent:'space-between',alignItems:'center',gap:15}}><div><div style={{fontSize:11,letterSpacing:'.12em',fontWeight:800,color:'#2d9b4c'}}>BATCH CREATED</div><h2 style={{fontSize:21,margin:'5px 0'}}>Generated serial numbers</h2><p style={{fontSize:12,color:'#718096'}}>Batch: {generated[0].batch_number}</p></div><button style={styles.primary} onClick={downloadCsv}>Download CSV ↓</button></div><div style={{marginTop:14,maxHeight:340,overflow:'auto',border:'1px solid #eef1f5',borderRadius:14}}>{generated.slice(0,100).map((r,i)=><div key={r.serial_number} style={{display:'flex',justifyContent:'space-between',gap:12,padding:'10px 14px',borderBottom:'1px solid #eef1f5',fontSize:12}}><span>{i+1}. <b>{r.serial_number}</b></span><span style={{color:'#0a9449',fontWeight:700}}>{r.manufacturing_date}</span></div>)}{generated.length>100&&<div style={{padding:12,textAlign:'center',fontSize:11,color:'#64748b'}}>Showing first 100 of {generated.length}. Use Download CSV for the complete batch.</div>}</div></section>}
 </div></div>
}
