'use client'

import { FormEvent, useEffect, useState } from 'react'
import { supabase } from '@/lib/supabase'

const statuses=[['received','Received'],['assigned','Assigned'],['technician_visit','Technician Visit'],['under_service','Under Service'],['resolved','Resolved'],['closed','Closed']] as const

type Complaint={
 complaint_number:string;registration_number:string|null;serial_number:string;model_code:string|null;product_name:string|null;full_name:string;mobile:string;email:string|null;address:string|null;city:string|null;state:string|null;pin_code:string|null;
 complaint_type:string;problem_description:string;purchase_date:string|null;preferred_visit_date:string|null;preferred_contact_time:string|null;service_address:string|null;service_city:string|null;service_state:string|null;service_pin:string|null;status:string;created_at:string;
 assigned_engineer_name:string|null;assigned_engineer_mobile:string|null;action_taken:string|null;assigned_at:string|null;closed_at:string|null;warranty_start_date:string|null;warranty_end_date:string|null;warranty_status:string|null;capacity_kw:number|null;production_date:string|null;product_image:string|null
}
type RegistrationProduct={registration_number:string;serial_number:string;model_code:string;product_name:string;capacity_kw:number;product_image:string|null;production_date:string|null;warranty_start_date:string;warranty_end_date:string;warranty_status:string;full_name:string;mobile:string;email:string|null;address:string;city:string;state:string;pin_code:string;purchase_date:string;invoice_number:string|null;dealer_name:string;purchase_type:string}

const statusLabel=(s:string)=>statuses.find(([v])=>v===s)?.[1]??s
const statusClass=(s:string)=>`statusPill status-${s.replace(/_/g,'-')}`
const fmt=(v:string|null|undefined)=>v?new Date(v+'T00:00:00').toLocaleDateString('en-IN',{day:'2-digit',month:'short',year:'numeric'}):'—'
const imageUrl=(value:string|null|undefined)=>{const raw=value?.trim();if(!raw)return '/olitec-generated-hero.jpg';if(/^https?:\/\//i.test(raw)||raw.startsWith('/'))return raw;const base=process.env.NEXT_PUBLIC_SUPABASE_URL?.replace(/\/$/,'');if(!base)return '/olitec-generated-hero.jpg';if(raw.startsWith('storage/v1/'))return `${base}/${raw}`;if(raw.includes('/'))return `${base}/storage/v1/object/public/${raw}`;return `${base}/storage/v1/object/public/products/${encodeURIComponent(raw)}`}
function friendlyError(error:any){const message=error?.message||'';const map:Record<string,string>={ENGINEER_DETAILS_REQUIRED:'Enter the assigned engineer name and contact number before assigning the complaint.',ACTION_TAKEN_REQUIRED:'Enter the action taken before closing the complaint.',CLOSED_COMPLAINT_CANNOT_BE_REOPENED:'A closed complaint cannot be reopened.'};const key=Object.keys(map).find(k=>message.includes(k));return key?map[key]:(message||'Something went wrong.')}

export default function ServiceAdminPage(){
 const [email,setEmail]=useState('');const [password,setPassword]=useState('');const [loggedIn,setLoggedIn]=useState(false);const [complaints,setComplaints]=useState<Complaint[]>([]);const [loading,setLoading]=useState(false);const [error,setError]=useState('');const [message,setMessage]=useState('');const [filter,setFilter]=useState('all');const [selected,setSelected]=useState<Complaint|null>(null);const [registrationProducts,setRegistrationProducts]=useState<RegistrationProduct[]>([]);const [detailsLoading,setDetailsLoading]=useState(false);const [engineerName,setEngineerName]=useState('');const [engineerMobile,setEngineerMobile]=useState('');const [actionTaken,setActionTaken]=useState('');const [editMode,setEditMode]=useState<'assigned'|'closed'|null>(null)
 useEffect(()=>{supabase.auth.getSession().then(({data})=>{if(data.session){setLoggedIn(true);loadComplaints()}})},[])
 async function loadComplaints(){setLoading(true);setError('');const {data,error}=await supabase.rpc('get_service_admin_complaints');if(error)setError(friendlyError(error));else setComplaints((data??[]) as Complaint[]);setLoading(false)}
 async function login(e:FormEvent){e.preventDefault();setLoading(true);setError('');const {error}=await supabase.auth.signInWithPassword({email,password});if(error){setError(error.message);setLoading(false);return}setLoggedIn(true);await loadComplaints()}
 async function logout(){await supabase.auth.signOut();setLoggedIn(false);setComplaints([]);setSelected(null)}
 async function openComplaint(c:Complaint){setSelected(c);setEngineerName(c.assigned_engineer_name||'');setEngineerMobile(c.assigned_engineer_mobile||'');setActionTaken(c.action_taken||'');setEditMode(null);setError('');setMessage('');setRegistrationProducts([]);if(c.registration_number){setDetailsLoading(true);const {data,error}=await supabase.rpc('get_service_registration_details',{p_registration_number:c.registration_number});if(!error)setRegistrationProducts((data??[]) as RegistrationProduct[]);setDetailsLoading(false)}}
 async function updateStatus(status:string){if(!selected)return;setLoading(true);setError('');setMessage('');const {error}=await supabase.rpc('update_service_complaint_status',{p_complaint_number:selected.complaint_number,p_status:status,p_engineer_name:engineerName.trim()||null,p_engineer_mobile:engineerMobile.trim()||null,p_action_taken:actionTaken.trim()||null});if(error)setError(friendlyError(error));else{setMessage(`Complaint ${selected.complaint_number} updated to ${statusLabel(status)}.`);await loadComplaints();setSelected(c=>c?{...c,status,assigned_engineer_name:engineerName.trim()||c.assigned_engineer_name,assigned_engineer_mobile:engineerMobile.trim()||c.assigned_engineer_mobile,action_taken:actionTaken.trim()||c.action_taken}:c);setEditMode(null)}setLoading(false)}

 if(!loggedIn)return <div className="adminPage adminLoginPage"><div className="adminLoginWrap"><header className="adminBrandRow"><div><img src="/olitec-logo.svg" alt="OLITEC" style={{width:180,height:'auto',display:'block'}}/><div className="adminSubtitle">Service Portal</div></div><span className="adminTopBadge">Service Admin</span></header><section className="adminLoginCard"><div className="adminEyebrow">SERVICE PORTAL</div><h1>Sign in to manage complaints</h1><p>Use the authorised OLITEC service desk account.</p><form onSubmit={login} className="adminForm"><label>Staff email</label><input type="email" placeholder="service@olitec.in" value={email} onChange={e=>setEmail(e.target.value)} required/><label>Password</label><input type="password" placeholder="Enter password" value={password} onChange={e=>setPassword(e.target.value)} required/>{error&&<div className="adminError">{error}</div>}<button disabled={loading} className="adminPrimaryButton">{loading?'Signing in…':'Sign in to dashboard →'}</button></form><button className="adminSecondaryButton" style={{width:'100%',marginTop:10}} onClick={()=>{window.location.href='/admin'}}>← Back to Admin Home</button></section><div className="adminFooter">OLITEC · Service Management</div></div></div>

 const filtered=filter==='all'?complaints:complaints.filter(c=>c.status===filter)
 return <div className="adminPage"><div className="adminShell"><header className="adminHeader"><div><img src="/olitec-logo.svg" alt="OLITEC" style={{width:170,height:'auto',display:'block'}}/><div className="adminSubtitle">Service Complaint Dashboard</div></div><div className="adminHeaderActions"><button onClick={()=>{window.location.href='/admin'}} className="adminSecondaryButton">← Admin Home</button><button onClick={loadComplaints} className="adminSecondaryButton">↻ Refresh</button><button onClick={logout} className="adminDarkButton">Sign out</button></div></header>
 {error&&<div className="adminAlert error">{error}</div>}{message&&<div className="adminAlert success">✓ {message}</div>}
 <section className="adminStats"><button className={`adminStat ${filter==='all'?'active':''}`} onClick={()=>setFilter('all')}><span>Total Complaints</span><strong>{complaints.length}</strong></button>{statuses.map(([v,l])=><button key={v} className={`adminStat ${filter===v?'active':''}`} onClick={()=>setFilter(v)}><span>{l}</span><strong>{complaints.filter(c=>c.status===v).length}</strong></button>)}</section>
 <section className="adminPanel"><div className="adminPanelHead"><div><h2>Service Complaints</h2><p>Select a complaint to view the complete customer, registered product and service record.</p></div><span className="adminCount">{filtered.length} shown</span></div><div className="adminTableHead"><span>Complaint</span><span>Customer</span><span>Product / Engineer</span><span>Issue / Visit</span><span>Status</span></div>{loading&&<div className="adminEmpty">Loading complaints…</div>}{!loading&&!filtered.length&&<div className="adminEmpty"><div className="emptyIcon">✓</div><strong>No complaints found</strong><p>There are no complaints in this status.</p></div>}{!loading&&filtered.length>0&&<div>{filtered.map(c=><button key={c.complaint_number} onClick={()=>openComplaint(c)} className="adminComplaintRow"><div><strong>{c.complaint_number}</strong><small>{new Date(c.created_at).toLocaleString('en-IN')}</small></div><div><strong>{c.full_name}</strong><small>{c.mobile}</small><small>{c.email||'No email'}</small></div><div><strong>{c.model_code||'—'}</strong><small>{c.serial_number}</small>{c.assigned_engineer_name&&<small style={{color:'#167c42'}}>Engineer: {c.assigned_engineer_name}</small>}</div><div><strong>{c.complaint_type}</strong><small>{c.preferred_visit_date?`Visit: ${fmt(c.preferred_visit_date)}`:'Visit date not set'}</small><small>{c.preferred_contact_time||''}</small></div><div><span className={statusClass(c.status)}>{statusLabel(c.status)}</span></div></button>)}</div>}</section>
 {selected&&<div className="adminOverlay" onMouseDown={e=>{if(e.target===e.currentTarget){setSelected(null);setRegistrationProducts([])}}}><section className="adminDrawer serviceDetailDrawer"><div className="drawerHead"><div><div className="adminEyebrow">SERVICE COMPLAINT</div><h2>{selected.complaint_number}</h2></div><button onClick={()=>{setSelected(null);setRegistrationProducts([])}} className="drawerClose">×</button></div><div className="drawerStatus"><span>Current status</span><b className={statusClass(selected.status)}>{statusLabel(selected.status)}</b></div>
 <div className="serviceDetailHero"><div className="serviceProductImage"><img src={imageUrl(selected.product_image)} alt={selected.product_name||'OLITEC Product'} onError={e=>{e.currentTarget.src='/olitec-generated-hero.jpg'}}/></div><div><span className="adminEyebrow">REGISTERED PRODUCT</span><h3>{selected.model_code||'OLITEC Product'}</h3><p>{selected.product_name||'Solar Inverter'} · {selected.capacity_kw||'—'} kW</p><strong>{selected.serial_number}</strong><div className={`warrantyAdminBadge ${selected.warranty_status==='Active'?'active':''}`}>Warranty: {selected.warranty_status||'Unknown'}</div></div></div>
 <div className="detailSectionTitle">Customer</div><div className="detailGrid">{[['Name',selected.full_name],['Mobile',selected.mobile],['Email',selected.email||'—'],['Address',selected.address||'—'],['City / State', [selected.city,selected.state,selected.pin_code].filter(Boolean).join(', ')||'—']].map(([l,v])=><div className="detailItem" key={l}><span>{l}</span><strong>{v}</strong></div>)}</div>
 <div className="detailSectionTitle">Registration & warranty</div><div className="detailGrid">{[['Registration',selected.registration_number||'—'],['Serial number',selected.serial_number],['Production',fmt(selected.production_date)],['Warranty from',fmt(selected.warranty_start_date)],['Warranty till',fmt(selected.warranty_end_date)],['Purchase date',fmt(selected.purchase_date)]].map(([l,v])=><div className="detailItem" key={l}><span>{l}</span><strong>{v}</strong></div>)}</div>
 {selected.registration_number&&<div className="relatedProducts"><div className="detailSectionTitle">All products in this registration</div>{detailsLoading?<div className="relatedLoading">Loading registered products…</div>:registrationProducts.map(p=><div key={p.serial_number} className={`relatedProduct ${p.serial_number===selected.serial_number?'current':''}`}><img src={imageUrl(p.product_image)} alt="" onError={e=>{e.currentTarget.src='/olitec-generated-hero.jpg'}}/><div><strong>{p.model_code}</strong><span>{p.product_name} · {p.capacity_kw} kW</span><small>{p.serial_number}</small></div><em>{p.warranty_status}</em></div>)}</div>}
 <div className="detailSectionTitle">Complaint</div><div className="detailGrid">{[['Complaint type',selected.complaint_type],['Registered',new Date(selected.created_at).toLocaleString('en-IN')],['Preferred visit',selected.preferred_visit_date?fmt(selected.preferred_visit_date):'Not specified'],['Contact time',selected.preferred_contact_time||'Any time'],['Service location',[selected.service_address,selected.service_city,selected.service_state,selected.service_pin].filter(Boolean).join(', ')||'—']].map(([l,v])=><div className="detailItem" key={l}><span>{l}</span><strong>{v}</strong></div>)}</div><div className="detailBlock"><span>Problem description</span><p>{selected.problem_description}</p></div>
 <div className="detailSectionTitle">Service</div><div className="detailGrid">{[['Assigned engineer',selected.assigned_engineer_name||'Not assigned'],['Engineer contact',selected.assigned_engineer_mobile||'—'],['Assigned at',selected.assigned_at?new Date(selected.assigned_at).toLocaleString('en-IN'):'—'],['Closed at',selected.closed_at?new Date(selected.closed_at).toLocaleString('en-IN'):'—']].map(([l,v])=><div className="detailItem" key={l}><span>{l}</span><strong>{v}</strong></div>)}</div>{selected.action_taken&&<div className="detailBlock"><span>Action taken</span><p>{selected.action_taken}</p></div>}
 {editMode==='assigned'&&<div className="adminEditBox"><h3>Assign engineer</h3><p>The customer's requested visit details are already recorded above.</p><label>Engineer name</label><input value={engineerName} onChange={e=>setEngineerName(e.target.value)} placeholder="Engineer name"/><label>Engineer contact</label><input value={engineerMobile} onChange={e=>setEngineerMobile(e.target.value)} placeholder="Mobile number" inputMode="tel"/><button className="adminPrimaryButton" disabled={loading} onClick={()=>updateStatus('assigned')}>{loading?'Saving…':'Save Assignment →'}</button></div>}
 {editMode==='closed'&&<div className="adminEditBox"><h3>Close complaint</h3><label>Action Taken</label><textarea value={actionTaken} onChange={e=>setActionTaken(e.target.value)} placeholder="Describe the service action, repair/replacement and final resolution…" rows={5}/><button className="adminPrimaryButton" disabled={loading} onClick={()=>updateStatus('closed')}>{loading?'Closing…':'Submit & Close Complaint →'}</button></div>}
 <div className="statusSection"><h3>Service workflow</h3><div className="statusGrid">{statuses.map(([v,l])=>{const closed=selected.status==='closed';return <button key={v} disabled={loading||(closed&&v!=='closed')} onClick={()=>v==='assigned'?setEditMode('assigned'):v==='closed'?setEditMode('closed'):updateStatus(v)} className={`statusAction ${selected.status===v?'selected':''}`}>{selected.status===v?'✓ ':''}{l}{v==='assigned'&&selected.status!=='assigned'?' · Enter engineer':''}{v==='closed'&&selected.status!=='closed'?' · Enter action':''}</button>})}</div></div>
 </section></div>}
 </div></div>
}
