'use client'

import { useEffect, useMemo, useState } from 'react'
import { supabase } from '@/lib/supabase'
import ProductAdminNav from '@/components/ProductAdminNav'

type ReportRow = { product_id: string; model_id: string; model_code: string; product_name: string; capacity_kw: number | null; mrp: number | null; warranty_months: number; serial_number: string; qr_code: string | null; production_month: string | null; batch_number: string | null; created_by: string | null; created_at: string | null; downloaded_at: string | null; download_count: number; product_status: string | null }
const styles: Record<string, React.CSSProperties> = {
 page:{height:'100vh',overflow:'hidden',background:'#f7f9fb',color:'#172033'},shell:{height:'100%',maxWidth:1700,margin:'0 auto',padding:'20px 34px 22px',boxSizing:'border-box',display:'flex',flexDirection:'column'},header:{display:'flex',justifyContent:'space-between',alignItems:'center',gap:20,flexShrink:0,marginBottom:16},actions:{display:'flex',gap:10,flexWrap:'wrap',justifyContent:'flex-end'},button:{border:'1px solid #dfe5ec',borderRadius:11,padding:'10px 15px',fontWeight:800,cursor:'pointer',background:'#fff',color:'#172033',whiteSpace:'nowrap'},primary:{border:0,borderRadius:12,padding:'11px 17px',fontWeight:800,cursor:'pointer',background:'#ff7a00',color:'#fff',whiteSpace:'nowrap'},card:{background:'#fff',border:'1px solid #e4e9ef',borderRadius:20,padding:20,boxShadow:'0 10px 35px rgba(23,32,51,.05)',minHeight:0,display:'flex',flexDirection:'column',flex:1,overflow:'hidden'},input:{width:'100%',height:44,padding:'10px 13px',border:'1px solid #dfe3ea',borderRadius:11,background:'#fff',color:'#172033',boxSizing:'border-box'}
}
function displayMonth(value:string|null){return value?new Date(value+'T00:00:00').toLocaleDateString('en-IN',{month:'long',year:'numeric'}):'—'}
function displayDate(value:string|null){return value?new Date(value).toLocaleString('en-IN',{dateStyle:'medium',timeStyle:'short'}):'—'}
function csvCell(value:unknown){return `"${String(value??'').replace(/"/g,'""')}"`}
function downloadCsv(rows:ReportRow[]){const header=['Product','Model','Capacity (kW)','MRP','Warranty','Serial Number','QR URL','Production Month','Batch Number','Created By','Created At','Downloaded At','Download Count','Status'];const lines=rows.map(r=>[r.product_name,r.model_code,r.capacity_kw??'',r.mrp??'',`${Math.round(r.warranty_months/12)} years`,r.serial_number,r.qr_code??'',displayMonth(r.production_month),r.batch_number??'',r.created_by??'',displayDate(r.created_at),displayDate(r.downloaded_at),r.download_count,r.product_status??''].map(csvCell).join(','));const blob=new Blob([header.map(csvCell).join(',')+'\n'+lines.join('\n')],{type:'text/csv;charset=utf-8'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`OLITEC-Serial-Generation-Report-${new Date().toISOString().slice(0,10)}.csv`;a.click();URL.revokeObjectURL(url)}
function errorText(error:any){const message=error?.message||'Something went wrong.';return message.includes('ADMIN_ACCESS_REQUIRED')?'Your account does not have Product Admin permission.':message}

export default function SerialGenerationReportPage(){
 const [loggedIn,setLoggedIn]=useState(false);const [email,setEmail]=useState('');const [password,setPassword]=useState('');const [loading,setLoading]=useState(false);const [error,setError]=useState('');const [rows,setRows]=useState<ReportRow[]>([]);const [search,setSearch]=useState('');const [modelFilter,setModelFilter]=useState('');const [monthFilter,setMonthFilter]=useState('');
 async function loadReport(){setLoading(true);setError('');const {data,error}=await supabase.rpc('admin_get_serial_generation_report');if(error)setError(errorText(error));else setRows((data||[]) as ReportRow[]);setLoading(false)}
 useEffect(()=>{supabase.auth.getSession().then(({data})=>{if(data.session){setLoggedIn(true);loadReport()}})},[])
 async function login(event:React.FormEvent){event.preventDefault();setLoading(true);setError('');const {error}=await supabase.auth.signInWithPassword({email,password});if(error){setError(errorText(error));setLoading(false);return}setLoggedIn(true);await loadReport()}
 async function logout(){await supabase.auth.signOut();setLoggedIn(false);setRows([])}
 const models=useMemo(()=>Array.from(new Set(rows.map(r=>r.model_code))).sort(),[rows]);const months=useMemo(()=>Array.from(new Set(rows.map(r=>r.production_month).filter(Boolean) as string[])).sort().reverse(),[rows]);
 const filtered=useMemo(()=>{const q=search.trim().toLowerCase();return rows.filter(r=>{const matchesSearch=!q||[r.product_name,r.model_code,r.serial_number,r.qr_code,r.batch_number,r.created_by].some(v=>String(v||'').toLowerCase().includes(q));const matchesModel=!modelFilter||r.model_code===modelFilter;const matchesMonth=!monthFilter||r.production_month===`${monthFilter}-01`||r.production_month===monthFilter;return matchesSearch&&matchesModel&&matchesMonth})},[rows,search,modelFilter,monthFilter])
 function clearFilters(){setSearch('');setModelFilter('');setMonthFilter('')}
 if(!loggedIn)return <div style={{...styles.page,display:'flex',alignItems:'center',justifyContent:'center',padding:20}}><section style={{...styles.card,flex:'none',width:'100%',maxWidth:560}}><img src="/olitec-logo.svg" alt="OLITEC" style={{width:190,display:'block',margin:'0 auto 12px'}}/><div style={{textAlign:'center',color:'#718096'}}>Serial Number Report</div><h1 style={{textAlign:'center',marginBottom:8}}>Generation Audit Report</h1><p style={{textAlign:'center',color:'#718096'}}>Sign in with your Product Administration account to view serial-number generation history.</p><form onSubmit={login}><label style={{display:'block',fontSize:12,fontWeight:800,color:'#475569',margin:'15px 0 7px'}}>Staff email</label><input style={styles.input} type="email" value={email} onChange={e=>setEmail(e.target.value)} required/><label style={{display:'block',fontSize:12,fontWeight:800,color:'#475569',margin:'15px 0 7px'}}>Password</label><input style={styles.input} type="password" value={password} onChange={e=>setPassword(e.target.value)} required/>{error&&<div style={{marginTop:14,padding:12,borderRadius:12,background:'#fff0f0',color:'#b42318'}}>{error}</div>}<button style={{...styles.primary,width:'100%',marginTop:18}} disabled={loading}>{loading?'Signing in…':'Sign in →'}</button></form><button style={{...styles.button,width:'100%',marginTop:10}} onClick={()=>{window.location.href='/admin/products'}}>← Back to Product Administration</button></section></div>
 return <div style={styles.page}><div style={styles.shell}><header style={styles.header}><div><img src="/olitec-logo.svg" alt="OLITEC" style={{width:170,display:'block'}}/><div style={{color:'#718096',fontSize:14,marginTop:5}}>Serial Number Generation Report</div></div><div style={styles.actions}><button style={styles.button} onClick={()=>{window.location.href='/admin'}}>← Admin Home</button><button style={{...styles.button,background:'#172033',color:'#fff'}} onClick={logout}>Sign out</button></div></header>
 <ProductAdminNav active="serial-report" />
 {error&&<div style={{padding:11,borderRadius:12,background:'#fff0f0',color:'#b42318',border:'1px solid #ffd4d1',marginBottom:12,flexShrink:0}}>{error}</div>}
 <section style={styles.card}><div style={{display:'flex',justifyContent:'space-between',alignItems:'center',gap:15,flexWrap:'wrap',flexShrink:0}}><div><div style={{fontSize:11,letterSpacing:'.12em',fontWeight:800,color:'#168a45'}}>SERIAL NUMBER AUDIT</div><h1 style={{margin:'5px 0',fontSize:28}}>Generated Serial Numbers</h1><p style={{margin:0,color:'#718096',fontSize:13}}>Complete product, serial, QR, batch and creation audit details.</p></div><div style={{display:'flex',gap:10,alignItems:'center'}}><strong>{filtered.length}</strong><span style={{color:'#718096',fontSize:13}}>of {rows.length} serials</span><button style={styles.primary} disabled={!filtered.length} onClick={()=>downloadCsv(filtered)}>Export CSV ↓</button></div></div>
 <div style={{display:'grid',gridTemplateColumns:'minmax(260px,2fr) minmax(160px,1fr) minmax(180px,1fr) auto',gap:10,marginTop:16,alignItems:'center',flexShrink:0}}><input style={styles.input} placeholder="Search product, model, serial, QR, batch or created by…" value={search} onChange={e=>setSearch(e.target.value)}/><select style={styles.input} value={modelFilter} onChange={e=>setModelFilter(e.target.value)}><option value="">All models</option>{models.map(model=><option key={model} value={model}>{model}</option>)}</select><select style={styles.input} value={monthFilter} onChange={e=>setMonthFilter(e.target.value)}><option value="">All production months</option>{months.map(month=><option key={month} value={month.slice(0,7)}>{displayMonth(month)}</option>)}</select><button style={styles.button} onClick={clearFilters}>Clear</button></div>
 <div style={{marginTop:16,flex:1,minHeight:0,overflow:'auto',border:'1px solid #e5eaf0',borderRadius:14}}>{loading?<div style={{padding:35,textAlign:'center',color:'#718096'}}>Loading serial report…</div>:filtered.length===0?<div style={{padding:45,textAlign:'center',color:'#718096'}}>No serial numbers match the selected filters.</div>:<table style={{width:'max-content',minWidth:'100%',borderCollapse:'separate',borderSpacing:0,fontSize:12}}><thead><tr>{['Product','Model','Capacity','MRP','Warranty','Serial Number','QR URL','Production Month','Batch Number','Created By','Created At','Download / Status'].map((h,i)=><th key={h} style={{position:'sticky',top:0,zIndex:2,textAlign:'left',padding:'11px 13px',background:'#f8fafc',borderBottom:'1px solid #dfe5ec',color:'#64748b',fontSize:10,textTransform:'uppercase',whiteSpace:'nowrap',minWidth:i===0?180:i===5?175:i===6?280:i===8?190:i===9?180:i===10?170:100}}>{h}</th>)}</tr></thead><tbody>{filtered.map(row=><tr key={row.product_id}><td style={{padding:'11px 13px',borderBottom:'1px solid #edf0f4',fontWeight:800,whiteSpace:'nowrap'}}>{row.product_name}</td><td style={{padding:'11px 13px',borderBottom:'1px solid #edf0f4',fontWeight:700,whiteSpace:'nowrap'}}>{row.model_code}</td><td style={{padding:'11px 13px',borderBottom:'1px solid #edf0f4',whiteSpace:'nowrap'}}>{row.capacity_kw??'—'} kW</td><td style={{padding:'11px 13px',borderBottom:'1px solid #edf0f4',fontWeight:700,whiteSpace:'nowrap'}}>₹{Number(row.mrp||0).toLocaleString('en-IN')}</td><td style={{padding:'11px 13px',borderBottom:'1px solid #edf0f4',whiteSpace:'nowrap'}}>{Math.round(row.warranty_months/12)} years</td><td style={{padding:'11px 13px',borderBottom:'1px solid #edf0f4',fontWeight:900,whiteSpace:'nowrap'}}>{row.serial_number}</td><td style={{padding:'11px 13px',borderBottom:'1px solid #edf0f4',maxWidth:300}}><a href={row.qr_code||'#'} target="_blank" rel="noreferrer" style={{color:'#2563eb',display:'block',maxWidth:280,overflow:'hidden',textOverflow:'ellipsis',whiteSpace:'nowrap'}} title={row.qr_code||''}>{row.qr_code||'—'}</a></td><td style={{padding:'11px 13px',borderBottom:'1px solid #edf0f4',whiteSpace:'nowrap'}}>{displayMonth(row.production_month)}</td><td style={{padding:'11px 13px',borderBottom:'1px solid #edf0f4',whiteSpace:'nowrap'}}>{row.batch_number||'—'}</td><td style={{padding:'11px 13px',borderBottom:'1px solid #edf0f4',whiteSpace:'nowrap'}}>{row.created_by||'—'}</td><td style={{padding:'11px 13px',borderBottom:'1px solid #edf0f4',whiteSpace:'nowrap'}}>{displayDate(row.created_at)}</td><td style={{padding:'11px 13px',borderBottom:'1px solid #edf0f4',whiteSpace:'nowrap'}}><strong>{row.download_count}×</strong>{row.downloaded_at?' · Downloaded':''}<div style={{fontSize:11,color:'#64748b',marginTop:2}}>{row.product_status||'—'}</div></td></tr>)}</tbody></table>}</div>
 <div style={{fontSize:11,color:'#718096',marginTop:8,flexShrink:0}}>Scroll inside the report area to view all serials. Use the bottom scrollbar for the remaining columns.</div>
 </section></div></div>
}
