create unique index if not exists service_admins_email_lower_uidx on public.service_admins (lower(email));

alter table public.service_admins
  add column if not exists display_name text not null default '',
  add column if not exists product_admin boolean not null default false,
  add column if not exists service_admin boolean not null default false,
  add column if not exists super_admin boolean not null default false,
  add column if not exists approved_at timestamptz;

update public.service_admins set display_name=coalesce(nullif(display_name,''),'Super Admin'), product_admin=true, service_admin=true, super_admin=true, active=true, approved_at=coalesce(approved_at,now()) where lower(email)='admin@gsons.co.in';

create or replace function public.ol_super_admin_allowed() returns boolean language sql stable security definer set search_path=public as $$ select exists(select 1 from public.service_admins sa where lower(sa.email)=lower(coalesce(auth.jwt()->>'email','')) and sa.active=true and sa.super_admin=true); $$;
create or replace function public.ol_product_admin_allowed() returns boolean language sql stable security definer set search_path=public as $$ select exists(select 1 from public.service_admins sa where lower(sa.email)=lower(coalesce(auth.jwt()->>'email','')) and sa.active=true and (sa.product_admin=true or sa.super_admin=true)); $$;
create or replace function public.ol_service_admin_allowed() returns boolean language sql stable security definer set search_path=public as $$ select exists(select 1 from public.service_admins sa where lower(sa.email)=lower(coalesce(auth.jwt()->>'email','')) and sa.active=true and (sa.service_admin=true or sa.super_admin=true)); $$;
create or replace function public.ol_admin_allowed() returns boolean language sql stable security definer set search_path=public as $$ select public.ol_product_admin_allowed() or public.ol_service_admin_allowed(); $$;

create or replace function public.get_admin_permissions() returns table(email text, display_name text, active boolean, product_admin boolean, service_admin boolean, super_admin boolean, approved_at timestamptz) language sql stable security definer set search_path=public as $$ select sa.email,sa.display_name,sa.active,sa.product_admin,sa.service_admin,sa.super_admin,sa.approved_at from public.service_admins sa where lower(sa.email)=lower(coalesce(auth.jwt()->>'email','')) limit 1; $$;
create or replace function public.admin_list_users() returns table(email text, display_name text, active boolean, product_admin boolean, service_admin boolean, super_admin boolean, created_at timestamptz, approved_at timestamptz) language sql security definer set search_path=public as $$ select sa.email,sa.display_name,sa.active,sa.product_admin,sa.service_admin,sa.super_admin,sa.created_at,sa.approved_at from public.service_admins sa where public.ol_super_admin_allowed() order by sa.super_admin desc,sa.active desc,sa.email; $$;
create or replace function public.admin_set_user_permissions(p_email text,p_active boolean,p_product_admin boolean,p_service_admin boolean) returns void language plpgsql security definer set search_path=public as $$ begin if not public.ol_super_admin_allowed() then raise exception 'SUPER_ADMIN_REQUIRED'; end if; if lower(trim(p_email))='admin@gsons.co.in' then raise exception 'SUPER_ADMIN_LOCKED'; end if; update public.service_admins set active=coalesce(p_active,false),product_admin=coalesce(p_product_admin,false),service_admin=coalesce(p_service_admin,false),approved_at=case when coalesce(p_active,false) then coalesce(approved_at,now()) else approved_at end where lower(email)=lower(trim(p_email)); if not found then raise exception 'ADMIN_USER_NOT_FOUND'; end if; end; $$;

create or replace function public.handle_new_admin_auth_user() returns trigger language plpgsql security definer set search_path=public as $$ begin insert into public.service_admins(email,display_name,active,product_admin,service_admin,super_admin) values(lower(new.email),coalesce(nullif(trim(new.raw_user_meta_data->>'display_name'),''),split_part(coalesce(new.email,''),'@',1)),false,false,false,false) on conflict ((lower(email))) do nothing; return new; end; $$;
drop trigger if exists on_auth_user_created_admin_profile on auth.users;
create trigger on_auth_user_created_admin_profile after insert on auth.users for each row execute function public.handle_new_admin_auth_user();

drop function if exists public.get_product_for_registration(text);
drop function if exists public.get_warranty_verification(text);
create or replace function public.get_product_for_registration(identifier text) returns table(product_id uuid,serial_number text,qr_code text,model_code text,product_name text,capacity_kw numeric,manufacturing_date date,warranty_months integer,product_image text) language sql security definer set search_path=public as $$ select p.id,p.serial_number,p.qr_code,pm.model_code,pm.product_name,pm.capacity_kw,p.manufacturing_date,pm.warranty_months,pm.image_url from public.products p join public.product_models pm on pm.id=p.model_id where p.serial_number=identifier or p.qr_code=identifier limit 1; $$;
create or replace function public.get_warranty_verification(p_registration_number text) returns table(registration_number text,serial_number text,model_code text,product_name text,capacity_kw numeric,warranty_months integer,warranty_start_date date,warranty_end_date date,status text,product_image text) language sql security definer set search_path=public as $$ select wr.registration_number,wr.serial_number,wr.model_code,wr.product_name,wr.capacity_kw,wr.warranty_months,wr.warranty_start_date,wr.warranty_end_date,wr.status,pm.image_url from public.warranty_registrations wr left join public.products p on upper(trim(p.serial_number))=upper(trim(wr.serial_number)) left join public.product_models pm on pm.id=p.model_id where (upper(trim(wr.registration_number))=upper(trim(p_registration_number)) or upper(trim(wr.serial_number))=upper(trim(p_registration_number))) and wr.status<>'cancelled' order by wr.id; $$;

create or replace function public.admin_get_product_catalog() returns table(model_id uuid,model_code text,product_name text,capacity_kw numeric,mrp numeric,warranty_years integer,warranty_months integer,image_url text,product_id uuid,serial_number text,qr_code text,manufacturing_date date,batch_number text,product_status text) language sql security definer set search_path=public as $$ select pm.id,pm.model_code,pm.product_name,pm.capacity_kw,pm.mrp,pm.warranty_years,pm.warranty_months,pm.image_url,p.id,p.serial_number,p.qr_code,p.manufacturing_date,p.batch_number,p.status from public.product_models pm left join public.products p on p.model_id=pm.id where public.ol_product_admin_allowed() order by pm.model_code,p.serial_number; $$;

create or replace function public.admin_create_product_model(p_model_code text,p_product_name text,p_capacity_kw numeric,p_mrp numeric,p_warranty_years integer,p_image_url text default null) returns table(model_id uuid,model_code text,product_name text,capacity_kw numeric,mrp numeric,warranty_years integer,warranty_months integer,image_url text) language plpgsql security definer set search_path=public as $$ declare v_model public.product_models%rowtype; begin if not public.ol_product_admin_allowed() then raise exception 'PRODUCT_ADMIN_ACCESS_REQUIRED'; end if; if nullif(trim(p_model_code),'') is null then raise exception 'MODEL_NUMBER_REQUIRED'; end if; if nullif(trim(p_product_name),'') is null then raise exception 'PRODUCT_NAME_REQUIRED'; end if; if coalesce(p_mrp,0)<=0 then raise exception 'MRP_REQUIRED'; end if; if coalesce(p_warranty_years,0)<1 or p_warranty_years>20 then raise exception 'INVALID_WARRANTY_YEARS'; end if; select * into v_model from public.product_models pm where upper(pm.model_code)=upper(trim(p_model_code)) limit 1; if v_model.id is null then insert into public.product_models(model_code,product_name,capacity_kw,warranty_months,warranty_years,mrp,image_url) values(trim(p_model_code),trim(p_product_name),p_capacity_kw,p_warranty_years*12,p_warranty_years,p_mrp,nullif(trim(p_image_url),'')) returning * into v_model; else update public.product_models pm set product_name=trim(p_product_name),capacity_kw=p_capacity_kw,warranty_months=p_warranty_years*12,warranty_years=p_warranty_years,mrp=p_mrp,image_url=case when nullif(trim(p_image_url),'') is not null then nullif(trim(p_image_url),'') else pm.image_url end where pm.id=v_model.id returning pm.* into v_model; end if; return query select v_model.id,v_model.model_code,v_model.product_name,v_model.capacity_kw,v_model.mrp,v_model.warranty_years,v_model.warranty_months,v_model.image_url; exception when unique_violation then raise exception 'MODEL_NUMBER_ALREADY_EXISTS'; end; $$;

create or replace function public.admin_generate_serial_batch(p_model_id uuid,p_production_month date,p_quantity integer,p_request_key uuid) returns table(model_code text,serial_number text,qr_code text,production_month date,batch_number text) language plpgsql security definer set search_path=public as $$ declare v_model public.product_models%rowtype;v_prefix text;v_month text;v_start bigint;v_batch text;i integer;v_serial text;v_existing_batch public.product_serial_batches%rowtype;v_created_by text:=lower(coalesce(auth.jwt()->>'email','unknown')); begin if not public.ol_product_admin_allowed() then raise exception 'PRODUCT_ADMIN_ACCESS_REQUIRED'; end if; if p_request_key is null then raise exception 'REQUEST_KEY_REQUIRED'; end if; select * into v_existing_batch from public.product_serial_batches b where b.request_key=p_request_key limit 1; if v_existing_batch.id is not null then raise exception 'BATCH_REQUEST_ALREADY_USED'; end if; select * into v_existing_batch from public.product_serial_batches b where b.model_id=p_model_id and b.production_month=p_production_month limit 1; if v_existing_batch.id is not null then raise exception 'BATCH_ALREADY_GENERATED_FOR_PRODUCTION_MONTH'; end if; select * into v_model from public.product_models pm where pm.id=p_model_id and pm.is_active=true limit 1; if v_model.id is null then raise exception 'PRODUCT_MODEL_NOT_FOUND'; end if; if p_production_month is null or extract(day from p_production_month)<>1 then raise exception 'PRODUCTION_MONTH_REQUIRED'; end if; if coalesce(p_quantity,0)<1 or p_quantity>10000 then raise exception 'INVALID_QUANTITY'; end if; v_prefix:=regexp_replace(upper(trim(v_model.model_code)),'[^A-Z0-9]','','g');v_month:=to_char(p_production_month,'YYMM');perform pg_advisory_xact_lock(hashtext(v_prefix||':'||v_month));select coalesce(max(nullif(regexp_replace(p.serial_number,'^'||v_prefix||v_month,'','')::text,'')::bigint),0)+1 into v_start from public.products p where p.model_id=v_model.id and upper(p.serial_number) like v_prefix||v_month||'%';v_batch:=v_prefix||'-'||to_char(p_production_month,'YYYYMM')||'-'||upper(substr(replace(gen_random_uuid()::text,'-',''),1,8));insert into public.product_serial_batches(batch_number,request_key,model_id,production_month,quantity,created_by) values(v_batch,p_request_key,v_model.id,p_production_month,p_quantity,v_created_by);for i in 0..p_quantity-1 loop v_serial:=v_prefix||v_month||lpad((v_start+i)::text,6,'0');insert into public.products(model_id,serial_number,qr_code,manufacturing_date,batch_number,status) values(v_model.id,v_serial,v_serial,p_production_month,v_batch,'manufactured');model_code:=v_model.model_code;serial_number:=v_serial;qr_code:=v_serial;production_month:=p_production_month;batch_number:=v_batch;return next;end loop;exception when unique_violation then raise exception 'SERIAL_NUMBER_CONFLICT';end; $$;
create or replace function public.admin_mark_serial_batch_downloaded(p_batch_number text) returns void language plpgsql security definer set search_path=public as $$ begin if not public.ol_product_admin_allowed() then raise exception 'PRODUCT_ADMIN_ACCESS_REQUIRED'; end if;update public.product_serial_batches set downloaded_at=coalesce(downloaded_at,now()),download_count=download_count+1 where batch_number=trim(p_batch_number);if not found then raise exception 'BATCH_NOT_FOUND';end if;end; $$;
create or replace function public.admin_get_serial_batch_for_redownload(p_batch_number text) returns table(model_code text,serial_number text,qr_code text,production_month date,batch_number text) language plpgsql security definer set search_path=public as $$ begin if not public.ol_super_admin_allowed() then raise exception 'SUPER_ADMIN_REQUIRED';end if;update public.product_serial_batches set download_count=download_count+1 where batch_number=trim(p_batch_number);if not found then raise exception 'BATCH_NOT_FOUND';end if;return query select pm.model_code,p.serial_number,p.qr_code,b.production_month,b.batch_number from public.product_serial_batches b join public.product_models pm on pm.id=b.model_id join public.products p on p.batch_number=b.batch_number where b.batch_number=trim(p_batch_number) order by p.serial_number;end; $$;

create or replace function public.get_service_admin_complaints() returns table(complaint_number text,registration_number text,serial_number text,model_code text,product_name text,full_name text,mobile text,complaint_type text,problem_description text,status text,preferred_visit_date date,preferred_contact_time text,service_city text,service_state text,created_at timestamptz,assigned_engineer_name text,assigned_engineer_mobile text,action_taken text,assigned_at timestamptz,closed_at timestamptz) language sql security definer set search_path=public as $$ select sc.complaint_number,sc.registration_number,sc.serial_number,sc.model_code,sc.product_name,sc.full_name,sc.mobile,sc.complaint_type,sc.problem_description,sc.status,sc.preferred_visit_date,sc.preferred_contact_time,sc.service_city,sc.service_state,sc.created_at,sc.assigned_engineer_name,sc.assigned_engineer_mobile,sc.action_taken,sc.assigned_at,sc.closed_at from public.service_complaints sc where public.ol_service_admin_allowed() and sc.status<>'cancelled' order by sc.created_at desc; $$;
create or replace function public.update_service_complaint_status(p_complaint_number text,p_status text,p_engineer_name text default null,p_engineer_mobile text default null,p_action_taken text default null) returns void language plpgsql security definer set search_path=public as $$ declare v_current text; begin if not public.ol_service_admin_allowed() then raise exception 'SERVICE_ADMIN_ACCESS_REQUIRED';end if;select status into v_current from public.service_complaints where complaint_number=trim(p_complaint_number) for update;if v_current is null then raise exception 'COMPLAINT_NOT_FOUND';end if;if lower(v_current)='closed' and lower(p_status)<>'closed' then raise exception 'CLOSED_COMPLAINT_CANNOT_BE_REOPENED';end if;if lower(p_status)='assigned' then if nullif(trim(p_engineer_name),'') is null or nullif(trim(p_engineer_mobile),'') is null then raise exception 'ENGINEER_DETAILS_REQUIRED';end if;update public.service_complaints set status='assigned',assigned_engineer_name=trim(p_engineer_name),assigned_engineer_mobile=trim(p_engineer_mobile),assigned_at=coalesce(assigned_at,now()) where complaint_number=trim(p_complaint_number);elsif lower(p_status)='closed' then if nullif(trim(p_action_taken),'') is null then raise exception 'ACTION_TAKEN_REQUIRED';end if;update public.service_complaints set status='closed',action_taken=trim(p_action_taken),closed_at=now() where complaint_number=trim(p_complaint_number);elsif lower(p_status) in ('received','technician_visit','under_service','resolved') then update public.service_complaints set status=lower(p_status) where complaint_number=trim(p_complaint_number);else raise exception 'INVALID_SERVICE_STATUS';end if;end; $$;