-- OLITEC customer feedback for closed service complaints
create table if not exists public.service_complaint_feedback (
  id bigint generated by default as identity primary key,
  complaint_number text not null unique,
  serial_number text not null,
  rating integer not null check (rating between 1 and 5),
  feedback text,
  created_at timestamptz not null default now()
);

create index if not exists idx_service_complaint_feedback_serial on public.service_complaint_feedback(serial_number);
alter table public.service_complaint_feedback enable row level security;
revoke all on table public.service_complaint_feedback from public, anon, authenticated;

create or replace function public.get_complaint_feedback(p_complaint_number text)
returns table (rating integer, feedback text, submitted_at timestamptz)
language sql security definer set search_path=public as $$
  select f.rating, f.feedback, f.created_at
  from public.service_complaint_feedback f
  join public.service_complaints c on c.complaint_number=f.complaint_number
  where upper(trim(f.complaint_number))=upper(trim(p_complaint_number))
    and lower(c.status)='closed'
  limit 1;
$$;
revoke all on function public.get_complaint_feedback(text) from public;
grant execute on function public.get_complaint_feedback(text) to anon, authenticated;

create or replace function public.submit_complaint_feedback(
  p_complaint_number text,
  p_serial_number text,
  p_rating integer,
  p_feedback text default null
)
returns void
language plpgsql security definer set search_path=public as $$
declare
  v_status text;
  v_serial text;
begin
  if nullif(trim(p_complaint_number),'') is null then raise exception 'COMPLAINT_NUMBER_REQUIRED'; end if;
  if nullif(trim(p_serial_number),'') is null then raise exception 'SERIAL_NUMBER_REQUIRED'; end if;
  if coalesce(p_rating,0)<1 or p_rating>5 then raise exception 'INVALID_RATING'; end if;

  select lower(status), serial_number into v_status, v_serial
  from public.service_complaints
  where upper(trim(complaint_number))=upper(trim(p_complaint_number))
  limit 1;

  if v_status is null then raise exception 'COMPLAINT_NOT_FOUND'; end if;
  if v_status<>'closed' then raise exception 'FEEDBACK_ONLY_FOR_CLOSED_COMPLAINTS'; end if;
  if upper(trim(v_serial))<>upper(trim(p_serial_number)) then raise exception 'SERIAL_NUMBER_MISMATCH'; end if;
  if exists(select 1 from public.service_complaint_feedback where upper(trim(complaint_number))=upper(trim(p_complaint_number))) then raise exception 'FEEDBACK_ALREADY_SUBMITTED'; end if;

  insert into public.service_complaint_feedback(complaint_number,serial_number,rating,feedback)
  values(trim(p_complaint_number),trim(p_serial_number),p_rating,nullif(trim(p_feedback),''));
end;
$$;
revoke all on function public.submit_complaint_feedback(text,text,integer,text) from public;
grant execute on function public.submit_complaint_feedback(text,text,integer,text) to anon, authenticated;
