-- OLITEC transactional notification events
-- Creates durable notification events for product registration and service complaints.
-- The notification-worker processes these pending events through Resend.

create table if not exists public.notification_events (
  id bigint generated by default as identity primary key,
  event_type text not null check (event_type in ('product_registered','complaint_received','complaint_closed')),
  registration_number text,
  complaint_number text,
  recipient_email text,
  admin_email text,
  status text not null default 'pending' check (status in ('pending','processing','sent','failed')),
  attempts integer not null default 0,
  created_at timestamptz not null default now(),
  sent_at timestamptz,
  last_error text
);

create unique index if not exists notification_events_dedupe_idx
  on public.notification_events(
    event_type,
    coalesce(registration_number,''),
    coalesce(complaint_number,'')
  );
create index if not exists notification_events_pending_idx
  on public.notification_events(status, created_at);

alter table public.notification_events enable row level security;
revoke all on public.notification_events from anon, authenticated;

create or replace function public.queue_olitec_notification()
returns trigger
language plpgsql
security definer
set search_path=public
as $$
begin
  if TG_TABLE_NAME='warranty_registrations' and TG_OP='INSERT' then
    insert into public.notification_events(event_type,registration_number,recipient_email)
    values('product_registered',NEW.registration_number,NULLIF(trim(NEW.email),''))
    on conflict do nothing;
    return NEW;
  end if;

  if TG_TABLE_NAME='service_complaints' and TG_OP='INSERT' then
    insert into public.notification_events(event_type,complaint_number,registration_number,recipient_email)
    values('complaint_received',NEW.complaint_number,NEW.registration_number,NULLIF(trim(NEW.email),''))
    on conflict do nothing;
    return NEW;
  end if;

  if TG_TABLE_NAME='service_complaints' and TG_OP='UPDATE' then
    if lower(coalesce(NEW.status,''))='closed' and lower(coalesce(OLD.status,''))<>'closed' then
      insert into public.notification_events(event_type,complaint_number,registration_number,recipient_email)
      values('complaint_closed',NEW.complaint_number,NEW.registration_number,NULLIF(trim(NEW.email),''))
      on conflict do nothing;
    end if;
    return NEW;
  end if;

  return NEW;
end;
$$;

drop trigger if exists warranty_registration_notification_trigger on public.warranty_registrations;
create trigger warranty_registration_notification_trigger
after insert on public.warranty_registrations
for each row execute function public.queue_olitec_notification();

drop trigger if exists service_complaint_notification_trigger on public.service_complaints;
create trigger service_complaint_notification_trigger
after insert or update of status on public.service_complaints
for each row execute function public.queue_olitec_notification();

-- The service-admin mailbox is configurable here. The notification worker reads
-- notification_settings.key='service_admin_email' and falls back to its secret.
create table if not exists public.notification_settings (
  key text primary key,
  value text not null,
  updated_at timestamptz not null default now()
);

alter table public.notification_settings enable row level security;
revoke all on public.notification_settings from anon, authenticated;

-- Keep the worker deployable even when the setting has not yet been entered.
-- Replace the value below with the registered Service Admin mailbox.
insert into public.notification_settings(key,value)
values('service_admin_email','')
on conflict (key) do nothing;
